### ISSUE TITLE
F# solution_4 value generator issue

### ISSUE THREAD

**Issue by dmannock** [PlummersSoftwareLLC/Primes#630] opened 2021-08-10 21:02 UTC
Hi,
I noticed there was a new F# implementation ([solution 4](https://github.com/PlummersSoftwareLLC/Primes/tree/drag-race/PrimeFSharp/solution_4)) that was ~10x faster. Obviously it piqued my interest having not seen this version of the algorithm so I dived in and wasn't disappointed in the interesting approach, however there appears to be an issue.

The [newPrimeSievefunction returns a sequence](https://github.com/PlummersSoftwareLLC/Primes/blob/drag-race/PrimeFSharp/solution_4/Program.fs#L45) (generator) but doesn't materialise the values? (except on the final run where ```Seq.length``` is invoked inside printResults) 

If you force the sequence to generate by invoking something like ```Seq.length``` in the loop the results differ drastically.

from
```Passes: 10370, Time: 5.000092, Avg: 0.000482, Limit: 1000000, Count: 78498, Valid: true```
to
```Passes: 1131, Time: 5.001963, Avg: 0.004423, Limit: 1000000, Count: 78498, Valid: true```

to confirm I replaced the returned Seq computation expression with an Array
``` [| yield 2; for i in 0 .. bitlmt do if isprimendx i then yield i + i + 3 |]```
and get similar results to forcing sequence value generation
```Passes: 1125, Time: 5.002213, Avg: 0.004446, Limit: 1000000, Count: 78498, Valid: true```

And to confirm the other way by replacing the returned sequence with ```Seq.empty``` which gives the same result as the initial run where the generator values are not materialised (except it will fail also validation on the final loop)
```
Passes: 10231, Time: 5.000471, Avg: 0.000489, Limit: 1000000, Count: 0, Valid: false
ERROR: invalid results
```

Sorry to be the bearer of bad news. The author seems much more experiences with the Sieve of Eratosthenes, maybe there's a tweak they know of? @GordonBGood

**Comment by rbergen** [comment] 2021-08-10 21:21
@GordonBGood As this concerns a solution you submitted, I was wondering if you would care to comment?

**Comment by rbergen** [comment] 2021-08-10 21:43
@dmannock It seems that the lazy evaluation of the sequence that you're describing is confirmed by the [F# language reference page on sequences](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences), which states in the first paragraph that _"Individual sequence elements are computed only as required, so a sequence can provide better performance than a list in situations in which not all the elements are used."_ 

It's obvious that setting up the structure for the calculation of the primes (represented by the sequence in this case) is not enough to be considered a solution that calculates prime sieves. For that, the primes have to actually be calculated. In this case, that means that the evaluation of the sequence needs to be triggered for every iteration of the main loop.

**Comment by GordonBGood** [comment] 2021-08-11 00:06
@rbergen, @dmannock:

> @dmannock It seems that the lazy evaluation of the sequence that you're describing is confirmed by the [F# language reference page on sequences](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences), which states in the first paragraph that _"Individual sequence elements are computed only as required, so a sequence can provide better performance than a list in situations in which not all the elements are used."_

> It's obvious that setting up the structure for the calculation of the primes (represented by the sequence in this case) is not enough to be considered a solution that calculates prime sieves. For that, the primes have to actually be calculated. In this case, that means that the evaluation of the sequence needs to be triggered for every iteration of the main loop.

**I take great exception to the above statement(s) that "the primes have to actually be calculated" (per pass)** as disqualifying my F# solution as the contributing document clearly states that the solutions can return a pre-sieved sieve buffer as one of the options (just that the sieving must occur on every pass of the timed loop **as is done here**), which is confirmed as none of the "Dave Plummer" solutions actually do the counting of the primes or enumeration and subsequent counting of the resulting primes within the timed loop but, rather, as a separate "method" call in the determining and validating of the results.  For my F# solution, all of the sieving has been completed with the call to the `loopndx` recursive function at line 43 within the initialization computed by the call to the `newPrimeSieve` function, which is computed on every pass, with the lazily computed countable results returned via the `seq<Prime>` sequence function result.

While it is true that an F# `Seq` is computed lazily, it does so based on an internal copy (a "capture") of the already sieved array which return of just the sieved array is allowed.  This is exactly the same as returning a lazy list of primes based on a forced "strict" sieving of the sieved array in Haskell (which as Haskell is a non-strict language, must be forced or the results won't reflect the sieving time), or the counting of the results using an iterator based on the already sieved array in any number of languages, which is allowed.  What would not be allowed would be to sieve the array buffer lazily only as the enumeration/counting of the results proceeded as that would hide the time for the actual sieving of the sieve buffer within the laziness of producing the results (which is exactly what Haskell does if the array sieving is not forced), but that is not the case here as the call of the recursive `loopndx` function has already happened within the `newPrimeSieve` function called once per pass.  In a similar way, I force the sieving of the `cmpsts` array by using the `seq` function in Haskell so that this has been computed strictly before the `primesSoEUnpeeled` and `primesSoEUnpeeledBlock` Haskell functions return (lines 48 and 73, respectively).

If this lazy counting were to be disallowed, than any solution that uses any form of iterator would also be disallowed (especially if such an iterator were returned directly) to do the enumeration and counting, which is idiomatic in many languages, just as many "functional style" languages can return a "closure" (meaning it has captured the sieved array in its captured environment) iterator as the returned value rather than a class containing a sieved buffer that could be counted directly or enumerated with a subsequent method call; the thing that should be disallowed if done would be lazily doing the sieving outside the timed loop as mentioned above, but none of my solutions "cheat" this way.

Although an Object Oriented Programming (OOP) class is preferred as it seems that Dave Plummer and many of the repo administrators may have more experience in OOP, it is not required as many of the languages do not provide facilities for the type of OOP that C++ provides and for many languages, the use of what limited OOP facilities they provide is discouraged as it is contrary to the language's main idioms; such a case is F#, which must provide OOP facilities in order to be compatible with DotNet libraries, but in idiomatic F# programming they are rarely used.  Haskell does not provide OOP at all, and building something like it would completely break the paradigms that it supports.

So @dmannock, as to the following:

> If you force the sequence to generate by invoking something like Seq.length in the loop the results differ drastically.

Of course the results differ drastically, as this is equivalent to making Dave Plummer count the number of primes within the timing loop for his implementations, or anyone else's implementation, made worse that the generations of `seq`'s in F# is particularly slow due to the use (slow but elegant) of computational expressions in their implementation - I only used them here because they were a convenient way to make the sequence and thus the count of primes for validation purposes outside the timing loop **which is their only purpose**.

It seems to me that you (and maybe @rbergen) are missing the point of the use of laziness as here as perhaps you are not primarily a functional programmer?

If you are going to require that the various solutions actually count the number of primes each pass, then none of the current solutions pass, and all/most of them will be extremely slow as the use of enumeration generally takes longer to compute than it does to do the actual sieving.  All of the solutions would then need to be converted to use of native "popcount" instructions to compute the "prime count" values necessary to validate the results, so that the counting time would not be too large a factor of **the sieving time, which seems to be to be the real parameter of interest in this benchmark.**

**Comment by GordonBGood** [comment] 2021-08-11 05:13
@rbergen:

If you can't see that the sieving in the functional language contributions such as F# or Haskell is actually completed on every pass and only the enumeration/counting is done lazily, it would be easy enough to refactor those contributions so that the creation functions return the sieved array, which would then be passed to other functions to enumerate/count or just count by other means such as by `popcount` as part of the results validation.  This is actually how polymorphism is accomplished in a functional language - by function composition in various forms.  Changing to use function composition to validate the results will have no effect on the speed of these contributions, just that the intermediate results will be in a different form in that the sieved array would be more obvious rather than being captured inside a closure.

**Comment by rbergen** [comment] 2021-08-11 06:22
@GordonBGood I'm going to try and keep this short, because I'm actually quite annoyed that I have to explain that the sieve calculations, as stipulated in the guidelines and discussed many times in this project, including with yourself, do need to be executed for a solution to qualify as a solution in the context of this project.

Your use of an F# sequence means that your unrolled loop is not executed, memory is not read or written, and indexing and bit twiddling does not take place _except for the last run_. It's like writing a function to do all those things, and then not invoking it. That is **not** in the spirit of this project.

If you really need a rule to accept this, then I can quote you one: _"Your benchmarked code returns either a list of primes or the is_prime array, containing the result of the sieve"_ It's one of the base rules that have been there from the beginning. (And yes, this rule is to be read as "for every iteration".)

We've come to consider storage of said array in the encapsulating object (class or alternative) as an acceptable alternative to "returns". That's irrelevant in this case, because as the F# language specifications state, the sequence doesn't represent either an array of flags nor a list of primes, until it is made into one. That's why it's possible to define, but not fully evaluate, infinite sequences in F#, as indicated in those same specifications. 

So, you'll either have to trigger the evaluation of the sequence so the calculations take place, or I will do it myself. Whether you do that by turning the sequence into an array (which is actually a well-documented approach to trigger sequence evaluation in the F# community), calculating its length or something else, is up to you. If you leave it to me, I will convert the sequence to an array, as that is the closest match with the rule I referred to earlier. 

Concerning your reference to other languages and solutions: if there are other languages/solutions who perform the preparations for the calculations but don't do the actual work, then thank you for pointing them out. They will then have to be fixed, as well.

**Comment by GordonBGood** [comment] 2021-08-11 06:59
@rbergen

> @GordonBGood I'm going to try and keep this short, because I'm actually quite annoyed that I have to explain that the sieve calculations, as stipulated in the guidelines and discussed many times in this project, including with yourself, do need to be executed for a solution to qualify as a solution in the context of this project.

Oh, I perfectly understand that **each and all of the sieve calculations must be performed for every pass through the timing loop** as per our previous discussions (and in fact, that wasn't the issue we were discussing in those other contributions as all of my contributions have done all of these computations for every pass, including this contribution; there we were only discussing order of operations); I, in turn, am annoyed having to explain that just because the returned `seq`/`iterator`/lazy list (as for Haskell) is lazily computed doesn't mean in any way that the filtering for base primes or the marking of composite numbers that are multiples of those base primes **must be** computed lazily.

> Your use of an F# sequence means that your unrolled loop is not executed, memory is not read or written, and indexing and bit twiddling does not take place _except for the last run_. It's like writing a function to do all those things, and then not invoking it. That is **not** in the spirit of this project.

**To the contrary, my use of an F# sequence DOES NOT MEAN that the unrolled loop is not executed nor that other marking operations have not fully completed!!!!!!!!!**; it only means that after all of the unrolled loops and other marking operations are completed **the final prime results can be found (or not as desired) lazily based on the captured fully sieved sieve buffer**.  Notice that this sequence is returned **after** all the sieving computations are complete as I explained in my first post!!!

> If you really need a rule to accept this, then I can quote you one: _"Your benchmarked code returns either a list of primes or the is_prime array, containing the result of the sieve"_ It's one of the base rules that have been there from the beginning. (And yes, this rule is to be read as "for every iteration".)
> 
> We've come to accept storage of said array in the encapsulating object (class or alternative) as an acceptable alternative to "returns". That's irrelevant in this case, because as the F# language specifications states, the sequence doesn't represent either an array of flags nor a list of primes, until it is made into one. That's why it's possible to define, but not fully evaluate, infinite sequences in F#, as indicated in those same specifications.

**It is relevant in this case.**  It seems you (and @dmannock) fail to grasp that a returned sequence written as I have done captures the **fully sieved buffer** in order to be lazily able to generate the found primes.  Thus the returned sequence contains the fully sieved array.  If I wanted to write a F# function that did the sieving lazily as the output primes were generated, I am perfectly capable of doing that but did not as that would not be within the specification.  In fact, in Haskell I had to fight with the compiler to force it to do the all of the work once per pass before returning the lazy list as with functional "referential transparency" a computed result is the same as the work set up to be done and it only wanted to do it once for all loops.

> So, you'll either have to trigger the evaluation of the sequence so the calculations take place, or I will do it myself. Whether you do that by turning the sequence into an array (which is a well-documented approach to trigger evaluation), calculating its length or something else, is up to you. If you leave it to me, I will convert the sequence to an array, as that is the closest match with the rule I referred to earlier.

Yes, that is the common way to do it, will make the contribution incredibly slow (as sequences are incredibly slow), and won't take advantage of my implementation.  So no, I won't leave it to you.

> Concerning your reference to other languages and solutions: if there are other languages/solutions who perform the preparations for the calculations but don't do the actual work, then thank you for pointing them out. They will then have to be fixed, as well.

The other language that returns a lazy list is of course Haskell, and whatever we agree to do with this contribution, I will also change that contribution as well.

As per my second post above, if you non-functional programmers can't see that the actual sieving work has already been done before the sequence is generated, I will refactor it (and the Haskell solution) so that the generating functions return a fully sieved array buffer, and separate functions are used to enumerate and/or count the results for validation.  You (and @dmannock) will see that the speed is exactly the same as the current solution (ie. I don't cheat).

I'm proceeding with that code refactoring now, as I am bored with this.

**Comment by rbergen** [comment] 2021-08-11 07:02
> I'm proceeding with that code refactoring now, as I am bored with this.

Good. So am I.

**Comment by rbergen** [comment] 2021-08-11 09:30
@GordonBGood Thank you for opening #633, which makes the solution conform and in doing so illustrates your point. I stand corrected.

There are still a few things to be said:
1. I am not here to frustrate contributors. In fact, the main reason I spend so much time on this project is that I find the selfless commitment of so many contributors' time, skills, knowledge and creativity very inspirational. 
2. I do understand the principles of functional programming, but I misread your code. That was an honest misunderstanding, and I apologize for it.
2. As an extension to the previous two points: I find your referral to another contributor and myself as "you non-functional programmers" dismissive and inappropriate. We can disagree on interpretations, misunderstandings will occur and the level of expertise on topics **will** vary from person to person. Be that as it may, using any of that as a foundation for value statements on individuals (or their work) is not acceptable.

**Comment by rbergen** [comment] 2021-08-11 09:41
@dmannock Thank you for looking into this and bringing this to our attention. I'll close this issue with #633 (and #634) in place.

**Closed as completed by rbergen** 2021-08-11 09:41 UTC

**Comment by GordonBGood** [comment] 2021-08-11 10:11
@rbergen:

> > I'm proceeding with that code refactoring now...

I've done the refactoring so that the creating functions return a complete sieved buffer and make it clear that this is done on every pass of the timing loop, then created a prime listing function to generate the found primes for the purpose of validation of results, for both the F# (PR #633) and Haskell (PR #634) "Unpeeled" solutions.

@dmannock may like to take an advance peek at this, as it didn't change the speed at all or maybe made it slightly faster as no closure with captured array is created (which requires some allocation).

@rbergen:

>There are still a few things to be said:
>
> 1. I am not here to frustrate contributors. In fact, the main reason I spend so much time on this project is that I find the selfless commitment of so many contributors' time, skills, knowledge and creativity very inspirational.

I, for one, do appreciate the time spent and the care taken, especially for you personally as you have been the person with whom I have had the most correspondence.  I often wonder how you find the time; for me it's easy as I am retired.

> 2. I do understand the principles of functional programming, but I misread your code. That was an honest misunderstanding, and I apologize for it.

All said and done, the code got changed, and perhaps it is better to do it the more conventional non-idiomatic-functional way in order to make it more clear and obvious to casual browsers how it works; I had already made some concessions that way anyway in using the `forM` monadic loop-look-alike in the Haskell code to make it obvious where the loops were.

> 3. As an extension to the previous two points: I find your referral to another contributor and myself as "you non-functional programmers" dismissive and inappropriate. We can disagree on interpretations, misunderstandings will occur and the level of expertise on topics will vary from person to person. Be that as it may, using any of that as a foundation for value statements on individuals (or their work) is not acceptable.

I'm truly sorry for the tone of that comment; it come out in a moment of annoyance as it seems so obvious to me (and perhaps to you now that you understand the code) that to force the code to count the number of resulting primes inside the timing loop is **of course** going to slow the code and is no kind of proof that the use of lazy sequences as I used them would have any contribution to the speed of the algorithm for what we are bench marking here.  Please forgive me for that flash of pique.

Although you and I usually can come to an agreement quite quickly once we understand each other's point of view, the thought of spending another day or two defending code for which the reason for the issue is quite illogical frustrated me, especially when it seemed that you could also see the point of the issue even though it is illogical.

I quote from the issue text "The `newPrimeSieve` function returns a sequence (generator) but doesn't materialise the values? (except on the final run where `Seq.length` is invoked inside `printResults`)".

In fact, none of the accepted contributions (or at least none that are very fast) "materialise the values" until they are enumerated and counted in the results validation phase **outside the timing loop**; the only difference is in the implementation details on whether this is done lazily or not.  Lazily (usually, and almost certainly in F#) can be slower than "strict"/non-lazy but it didn't matter, it's **outside the timing**.

Anyway, we got past it, and the issue is closed, enough already.

**Comment by rbergen** [comment] 2021-08-11 10:28
Thank you for taking the time to write that response, I appreciate it. 

>  I often wonder how you find the time; 

What really helps with _making_ the time is that I really enjoy doing this. Somewhat awkwardly, the coronavirus also helps. Working from home saves me about 2 hours of travel time (and traffic frustrations) on most days compared to earlier times.

> for me it's easy as I am retired.

I'm glad to hear it. That's something I'm still working on. And will be for some time I think, because I again failed to win the Dutch national lottery, yesterday.

> Anyway, we got past it, and the issue is closed, enough already.

I whole-heartedly agree.

**Comment by dmannock** [comment] 2021-08-11 10:50
Wow, a lot has happened since I looked last night!

Thanks for the clarification. I must admit I misread the intent of the newPrimeSieve with the signature returning seq in the context of this challenge. For some reason I had it stuck in my head the seperate functions for those tasks from the original implementation for ```runSieve``` and ```countPrimes```. Maybe I was blinded by the interesting algorithm, maybe I just needed a fresh pair of eyes. It all makes sense on a fresh day, sorry for causing any problems.

On the plus side it now runs ~8% faster on my machine.
```Passes: 11203, Time: 5.000200, Avg: 0.000446, Limit: 1000000, Count: 78498, Valid: true```
Another thing this challenge has highlighted is that even small tweaks can alter the generated IL to be more performant. Even by seemingly doing more work in code. For example, adding functions, unused args, arg position, etc.

It's now closed the gap to other languages, given you both appear to be experts on the Sieve of Eratosthenes I'm wondering if there remains a bit more performance to be squeezed out :)

All in all Nice and interesting approach!

**Comment by GordonBGood** [comment] 2021-08-11 11:36
@dmannock:

 
> On the plus side it now runs ~8% faster on my machine.
> `Passes: 11203, Time: 5.000200, Avg: 0.000446, Limit: 1000000, Count: 78498, Valid: true`

Yes, I think it is faster due to not needing to do the allocations for the closure(s) and captured environment(s).

> It's now closed the gap to other languages, given you both appear to be experts on the Sieve of Eratosthenes I'm wondering if there remains a bit more performance to be squeezed out :)

For extra performance above this, I don't think there is very much left for an F# solution as it is limited in being a Just-In-Time (JIT) compiled language with the use of raw memory and pointers (`IntPtr`) intended to be used with marshalling with native languages and have detuned performance in order to discourage their general use.

This latest version is running at about 2.4 CPU clock cycles per culling/marking operation, which is pretty high for a JIT language.  The main two reasons it is faster than any of the previous solutions is that "unpeeling" simplifies the marking loops and that I include the array length in the loop limit so that it doesn't automatically add array bounds checking in recognizing it's unnecessary.  There is still a loss of time due to "cache thrashing" but if we try to do something about that by culling in cache-sized blocks, we likely will lose some of the benefit of eliminating the bounds checks.  It's possible that manually dividing the sieve buffer into cache-sized blocks and sieving those may help a little, but it will also add to the overhead, so likely not very much, maybe up to 5 to 10 percent.

I have written the Sieve of Eratosthenes in other fully native compiled languages for smallish ranges such as this one million to run in just over one CPU clock cycle per marking operation, but that either requires a CPU with a 64 Kilobyte data L1 cache (like the Apple M1...) or page segmentation but the the use of the latter is outside the specification of what we are allowed to do here and keep the `base` algorithm categorization.  So we lose about 25% to run at about 1.25 CPU clock cycles per operation just due to "cache thrashing" on a CPU with a 32 Kilobyte L1 data cache as most common CPU's have.

That said, if these same techniques are used in C# it will have very similar performance, so the performance isn't really due to F# (although the F# code is more elegant in my opinion).

These fastest algorithms require another "Extreme Loop Unrolling" technique that can be used with native code compiling languages but JIT compiling can't handle the register optimizations.  Interestingly, this technique works somewhat with the Ahead-Of-Time (AOT) compilation used by Julia, although it doesn't optimize quite to the same level as languages that are fully native code compiled.  On your machine it would likely run at about 20,000 passes in five seconds using this technique in Julia.  I am working on submitting such a Julia solution.

The fastest that any code with any acceptable algorithm can run in the fastest languages (such as Nim) is something like 25,000 passes per five seconds on your machine and still be categorized as `base` but that will never be F#, which is always going to be about half that speed.
