### ISSUE TITLE
Licenses and Build support for Delphi

### ISSUE THREAD

**Issue by jimmckeeth** [PlummersSoftwareLLC/Primes#199] opened 2021-05-24 00:19 UTC
I see that Delphi was disqualified for concerns about having a license. I'm happy to provide a few Delphi licenses for the purposes of testing. I'm a Developer Advocate and we are happy to provide licenses for projects like this. Comment on here if you are interested and we can figure out how many licenses you need.

**Comment by rbergen** [comment] 2021-05-24 07:06
First off, thank you for reaching out to us.

It is important to note that we did not disqualify the Delphi entry in any way. As far as we're concerned, it is a full member of the set of solutions in the repo. However, what we also did not do was add a Dockerfile to it that will allow it to be included in the automated benchmarking and reporting runs. As you state, that was indeed because of concerns that we might end up unwillingly violating applicable license terms.

What we would need to be able to include the Delphi entry in the benchmark and reporting runs, is a Docker image that includes:

- the command-line tooling needed to compile the Delphi source code to an executable file. 
- any runtime components that are needed to then run that executable.

For our purposes, we do not need any additional (developer) tooling, like the IDE.

The number of licenses is exactly where we got stuck. At the moment, I know that at least 4 people are running the benchmark and generating reports, being the members of the organization account that this repository now resides under. However, by design, the repository itself includes source code and instructions to run the benchmark. That means that the benchmark _could_ be run on any system to which the repository is cloned. With the setup being what it is, we have no way to limit that number of systems, nor do we want to.

At least from my personal perspective, this project is very much about inclusivity of languages, algorithms and approaches, while acknowledging that that brings a challenge in making balanced comparison between entries. In line with that, we would love to include the Delphi entry in the benchmarking and reporting runs, if we can find a licensing solution that supports what I have described in this comment.

**Comment by jimmckeeth** [comment] 2021-05-24 21:40
Great, thanks, I believe I can make this happen...

Are you running Docker containers on Windows? Our build process is currently tied to Windows, but I can probably make it work on Linux if necessary...

I can provide 4 licenses for the core team involved. If additional people want to be involved later then they can use a free trial or CE license, their own license, or we can address that when the time comes.

**Comment by davepl** [comment] 2021-05-24 23:43
I test it under both Windows and Linux.  I’ve tried it under MacOS, but only the first two really matter me!  I could live without the Delphi in one of them though.

Cheers
Dave

**Comment by jimmckeeth** [comment] 2021-05-24 23:45
Is the Docker build environment running Windows or Linux? It can build for all 3 easy, but just want to make sure I provide the right Docker container.

**Comment by rbergen** [comment] 2021-05-25 08:48
Currently, all Docker images we use are themselves based on Linux base images (we prefer Alpine, but also use Ubuntu where needed).  

The benchmark consists of a Makefile that builds and runs Docker images for all solutions that contain a Dockerfile, and therefore requires make and Docker to be installed and working. This is thus really aimed at use from a *NIX environment. Personally, I've seen it work on Linux installations running on bare metal, on Windows within WSL2, and on MacOS. From a hardware architecture perspective, we encourage support for amd64 and arm64.

**Comment by marghidanu** [comment] 2021-06-21 20:31
Is this issue still valid?

**Comment by jimmckeeth** [comment] 2021-06-22 05:30
Yeah, I'm working on a docker image for you.

**Comment by rbergen** [comment] 2021-07-04 12:07
I was wondering if there is an expectation concerning when the image will be available? The reason I am asking is that, in follow-up to a new YouTube video on the project, we now have two new PRs open (#264 and #281) related to Delphi implementations. I would prefer to work towards merging them with a Dockerfile in place, if that is possible within a reasonable timeframe.

**Comment by KimMadsen** [comment] 2021-07-04 21:03
Will a precompiled 32bit and 64bit version do as an intermediate solution, until Embarcadero / Jim produce a Docker image?

**Comment by rbergen** [comment] 2021-07-04 21:16
Short answer: no. To avoid any discussions about the validity of the results, we need the benchmark tooling to use the submitted source code as a starting point. That translates to the requirement that any executables need to be built from source code by the benchmark tooling itself, using a verifiable (i.e. human-readable) approach.

On top of that, we don't want to include any binaries in the repo, to avoid hidden licensing issues or other types of nastiness that are practically impossible to identify in binary format.

**Comment by KimMadsen** [comment] 2021-07-04 22:01
I understand the reason. However would it not be possible to accept the source code solutions I entered, even if there are no current Docker image? Then people can choose to manually download and compile (and perhaps learn) from the code.

**Comment by rbergen** [comment] 2021-07-04 22:14
I'm not saying we won't. My current plan is to wait for @jimmckeeth's answer, and take it from there. If we can combine things it will reduce the number of change cycles, which would save this repo's maintainers a meaningful amount of time. Between day jobs and other things, we do have to consider that.

**Comment by rbergen** [comment] 2021-08-17 21:03
Based on lack of input from @jimmckeeth over the past 8 weeks, I'm concluding that it is not possible for Embarcadero to provide build and run support for Delphi in the context of this project. I'm closing this issue for that reason. If developments occur that warrant my conclusion to be revised, I'm very happy to follow up on this.

**Closed as completed by rbergen** 2021-08-17 21:03 UTC
