### ISSUE TITLE
There are no instructions for running this suite

### ISSUE THREAD

**Issue by rayray** [PlummersSoftwareLLC/Primes#203] opened 2021-05-24 23:42 UTC
Please add instructions to the README for running the entire suite. Specifically Windows, although any amount of instructions for any platform would be an improvement!

**Comment by marghidanu** [comment] 2021-05-25 04:39
We haven’t really tested on Windows. Probably it would work under WSL, assuming you’ve got Docker and make installed you just need to type: `make` and wait :)

**Comment by rbergen** [comment] 2021-05-25 08:41
@rayray I can confirm it works on WSL2 (and yes, the 2 matters), with Docker Desktop, bash and make installed; I've tested this myself on Ubuntu 20.04 LTS. However, within that context, there is a significant performance impact (up to 50%) concerning whatever runs within Docker, which is basically everything. We therefore recommend running the benchmark on a "bare" Linux distro. 

The basic instructions really are as simple as @marghidanu indicates. On Windows: 

- install Docker Desktop, WSL2, and a WSL2 Linux distro (again, Ubuntu 20.04 LTS is known to work)
- within that distro: install bash and make, run `make`, wait

As this is a collaborative project, feel free to draft a document (my suggestion would be a separate BENCHMARK.md that we can then link to from the README) with more elaborate instructions.

**Comment by fvbakel** [comment] 2021-05-27 15:07
I was looking for the same information. I think it is a good idea to write such a document. I have made a first draft proposal here:
https://github.com/fvbakel/Primes/commit/b96772c24f15db7568f2133e63070e297325cb67. I can add more details on the Windows instructions and create a pull request to solve this issue.

**Comment by rbergen** [comment] 2021-05-27 15:34
@fvbakel Thank you very much for picking this up, it's highly appreciated!

I just look at your first draft proposal, and I think it's a good start. Have you thought on how (and when) would you like to receive feedback/input?

**Comment by fvbakel** [comment] 2021-05-27 16:47
@rbergen Thank you for your quick response. If you feel that this first draft is in the right direction, then I can further extend it next week with the windows and mac os instructions in a similar way.

**Comment by rbergen** [comment] 2021-05-27 17:16
Yes, I think it's definitely in the right direction. Some comments I can make off the cuff:

- Although I have seen the benchmark suite run on Windows 10 within WSL2 and with Docker Desktop, the impact on performance is really significant in that setup (up to 50%, as I wrote before). If you ask me, the section on Windows should start with a clear statement that using that setup is not recommended. 
- Furthermore, for Windows, I would not spend time on describing alternatives to the Windows 10/WSL2/Docker Desktop combination. I'm almost certain that the Cygwin path will not work (the WSL2 setup works because a lot of work was put into making it work by Docker and Microsoft, still with the performance penalty already mentioned), and the virtual machine scenario is basically the Linux option in a virtualized context, with a performance impact of its own.
- Personally, I have seen the benchmark suite run on MacOS with Xcode command-line tools (for make) and Docker Desktop installed. Instructions for installing the Xcode command-line tools can easily be found online, and usually boil down to running `xcode-select --install` in a terminal window.

**Comment by Anders1971** [comment] 2021-05-28 19:55
> I was looking for the same information. I think it is a good idea to write such a document. I have made a first draft proposal here:
> [fvbakel@b96772c](https://github.com/fvbakel/Primes/commit/b96772c24f15db7568f2133e63070e297325cb67). I can add more details on the Windows instructions and create a pull request to solve this issue.

I look forward for more information on how execute the program on Windows 10
Steps I have done. 

1. Win10 Cmd: 'git clone https://github.com/PlummersSoftwareLLC/Primes.git' to local disk, folder c:\primes
2. Downloaded Docker and installed Docker. Updated Docker and it is running.
3. Ubuntu inside Docker, using the command "docker run -t -i ubuntu /bin/bash"
4. I have also installed ubuntu via Microsoft store.
5. ??

I do not know if step 3 or 4 is correct?

Really looking forward to the readme. 

First time git user, First time Docker user, First time ubuntu user. First time posting at GitHub.

**Comment by fvbakel** [comment] 2021-05-28 20:09
@Anders1971 I did some research today and found that wsl2 must be installed before docker. Further more Ubuntu needs to be set as the distribution in wsl2, no need to do step3. 
My advice is to uninstall docker, make sure wsl2 is installed with the Ubuntu 18.04 distribution. And then follow these draft instructions <https://github.com/fvbakel/Primes/blob/issues/203/BENCHMARK.md>. I have not tested these on a fresh Windows 10 yet, planning to do that next week.

**Comment by rbergen** [comment] 2021-06-17 09:26
Closing this in relation to the merge of #213.

**Closed as completed by rbergen** 2021-06-17 09:26 UTC
